repository_type: pipeline
lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-forte_logo_light.png
  - docs/images/nf-core-forte_logo_light.png
  - docs/images/nf-core-forte_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/workflows/branch.yml
  - .github/workflows/ci.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  - conf/igenomes.config
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - process.cpus
  - process.memory
  - process.time
  - custom_config
  multiqc_config:
  - report_comment
  files_unchanged:
  - .github/ISSUE_TEMPLATE/bug_report.yml
  readme:
  - nextflow_badge
