show_analysis_paths: False
extra_fn_clean_trim:
  - "htseq.count"
export_plots: true

use_filename_as_sample_name:
  - kallisto

custom_data:
  htseq_expression_genstats:
    plot_type: "generalstats"
    pconfig:
      - GeneCount:
          title: "Gene Count"
          format: "{:,.0f}"
          description: "HTSeq: Number of genes with detected expression"
  kallisto_expression_genstats:
    plot_type: "generalstats"
    pconfig:
      - GeneCount:
          title: "Gene Count"
          format: "{:,.0f}"
          description: "Kallisto: Number of genes with detected expression"
  assess_strandedness:
    plot_type: "generalstats"
    pconfig:
      - input_strandedness:
          title: "Input Strandedness"
          description: "Strandedness entered in input samplesheet"
      - inferred_strandedness:
          title: "Inferred Strandedness"
          description: "Strandedness determined from PICARD_COLLECTRNASEQMETRICS results"
      - input_strand_correct:
          title: "Strandedness Correct"
          description: "Correctness of input strandedness"

sp:
  htseq_expression_genstats:
    fn: "*.htseq.summary.txt"
  kallisto_expression_genstats:
    fn: "*.kallisto.customsummary.txt"
  assess_strandedness:
    fn: "*.strandedness.txt"
